final/WebsiteMVC/Controllers/UserAccountController.cs
using System;
using System.Web.Mvc;
using Parse;
using System.Collections.Generic;
using Facebook;
using System.Web.Security;
using System.Web;

namespace WebsiteMVC.Controllers
{
    public class UserAccountController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Login(FormCollection coll)
        {
            string returnUrl = coll["returnUrl"];
            string username = coll["username"];
            string password = coll["password"];

            Navigation.State.CurrentUser = await DAL.UserAccountDB.LoginUser(username, password);
            if(Navigation.State.CurrentUser == null) // failed to log in 
            {
                Navigation.State.CurrentUser = null;
                Models.UserModel user = new Models.UserModel();
                user.login = false;
                return View(user);
            }

            // login successfull
            return new RedirectResult(returnUrl);
        }


        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> Register(FormCollection coll)
        {
            Models.UserModel user = new Models.UserModel();
            string Business = coll["isBusiness"];
            bool isBusiness = false;
            if (Business!=null && Business.Equals("True"))
                isBusiness = true;
            string firstName = coll["firstname"];
            string lastName = coll["lastname"];
            string returnUrl = coll["returnUrl"];
            string email = coll["email"];
            string userName = coll["username"];
            string password = coll["password"];
            string confirmPassword = coll["confirmpassword"];

            if (password.Equals(confirmPassword))
            {
                string tryRegister = await DAL.UserAccountDB.RegisterNewUser(userName, firstName, lastName, email, password, isBusiness);
                if (tryRegister.Equals("sucessfull"))
                {
                    BLL.User currentUser = await DAL.UserAccountDB.RegisterNewUser();
                    Navigation.State.CurrentUser = currentUser;
                    if (isBusiness)
                        return RedirectToAction("CompleteBusinessDetails", "Business"); //redirect to dashboard to complete business details page
                    return new RedirectResult(returnUrl);
                }
                else {
                    user.register = false;
                    user.registerError = tryRegister;
                    return View(user);
                }
            }
            else {
                user.register = false;
                user.registerError = "Passwords are not the same";
                return View(user);
            }   
        }
        
        
        public ActionResult LogOut(string returnUrl)
        {
            Parse.ParseUser.LogOut();
            HttpCookie getCurrentCookie = Request.Cookies[Constants.COOKIE_NAME];
            HttpContext.Response.Cookies.Remove(Constants.COOKIE_VALUES_USERID);
            HttpContext.Response.Cookies.Remove(Constants.COOKIE_VALUES_AUTH);
            getCurrentCookie.Expires = DateTime.Now.AddDays(-1);
            getCurrentCookie.Value = null;
            HttpContext.Response.SetCookie(getCurrentCookie);
            Navigation.State.CurrentUser = null;
            return new RedirectResult(returnUrl);
        }

        [AllowAnonymous]
        public ActionResult ChangePassword()
        {
            Models.UserModel user = new Models.UserModel();
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> ChangePassword(FormCollection coll)
        {
            string email = coll["email"];
            ParseObject reset = await DAL.UserAccountDB.ResetUserPassword(email);

            Models.UserModel user = new Models.UserModel();
            user.changePasswordMailSent = true;
            return View(user);
        }








        // ------ Facebook Login ------- // 
        private Uri RedirectUri
        {
            get
            {
                var uriBuilder = new UriBuilder(Request.Url);
                uriBuilder.Query = null;
                uriBuilder.Fragment = null;
                uriBuilder.Path = Url.Action("FacebookCallback");
                return uriBuilder.Uri;
            }
        }



        public async System.Threading.Tasks.Task<ActionResult> LoginWithFacebook()
        {
            var fb = new FacebookClient();
            var loginUrl = fb.GetLoginUrl(new
            {
                client_id = "578999652278537",
                client_secret = "0e92edc25ebde0bb206ae1d2dfeacd4b",
                redirect_uri = RedirectUri.AbsoluteUri,
                response_type = "code",
                scope = "email"
            });

            return Redirect(loginUrl.AbsoluteUri);

        }


        public ActionResult FacebookCallback(string code)
        {
            var fb = new FacebookClient();
            dynamic result = fb.Post("oauth/access_token", new
            {
                client_id = "578999652278537",
                client_secret = "0e92edc25ebde0bb206ae1d2dfeacd4b",
                redirect_uri = RedirectUri.AbsoluteUri,
                code = code
            });

            var accessToken = result.access_token;

            // Store the access token in the session for farther use
            Session["AccessToken"] = accessToken;

            // update the facebook client with the access token so
            // we can make requests on behalf of the user
            fb.AccessToken = accessToken;

            // Get the user's information, like email, first name, middle name etc
            dynamic me = fb.Get("me?fields=first_name,middle_name,last_name,id,email");
            string email = me.email;
            string firstname = me.first_name;
            string middlename = me.middle_name;
            string lastname = me.last_name;

            // Set the auth cookie
            FormsAuthentication.SetAuthCookie(email, false);
            return RedirectToAction("Index", "Home");
        }


    }
}

final/WebsiteMVC/Views/UserAccount/ChangePassword.cshtml
@model WebsiteMVC.Models.UserModel

@{
    ViewBag.Title = "איפוס סיסמא";
}


<br />
<div class="container">


    @if (Model.changePasswordMailSent)
    {
        <h2>על מנת לסיים את התהליך שלחנו לך אי-מייל, אנא הכנס\י לדואר האלקטרוני על מנת לבחור סיסמא חדשה  </h2>
    }
    else
    {
        <div class="row" id="changePass">
            <div class="col-md-8">
                @using (Html.BeginForm("ChangePassword", "UserAccount", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <input type="hidden" name="returnUrl" value="@Request.Url.GetLeftPart(UriPartial.Authority)" />

                    <h2> איפוס סיסמא בקליק </h2>
                    <hr />

                    <div class="form-group">
                        <div class="col-md-3">
                            אי-מייל:
                        </div>
                        <div class="col-md-9">
                            <input type="text" name="email" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="איפוס סיסמא" class="btn btn-default" />
                        </div>
                    </div>
                }
            </div>
        </div>
    }
    
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

final/WebsiteMVC/Views/UserAccount/Login.cshtml
@model WebsiteMVC.Models.UserModel

@{
    ViewBag.Title = "Log in";
}
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '578999652278537',
      xfbml      : true,
      version    : 'v2.5'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<br />
<div class="container">

@if (Model!=null && !Model.login)
{
    <h2 style="color: #000000; margin-right: 25px;"> אירעה שגיאה בהתחברות, נסה שוב </h2>
}

<div class="row">
    <div class="col-md-8">
            @using (Html.BeginForm("Login", "UserAccount",  FormMethod.Post))
            {
                @Html.AntiForgeryToken()

                <input type="hidden" name="returnUrl" value="@Request.Url.GetLeftPart(UriPartial.Authority)" />
                <h2> התחבר עכשיו למשתמש שלך באתר </h2>
                <hr />

                <div class="form-group">
                    <div class="col-md-3">
                        שם משתמש:
                        </div>
                        <div class="col-md-9">
                            <input type="text" name="username" />
                        </div>
                    </div>
                <div class="form-group">
                    <div class="col-md-3">
                        סיסמא
                        </div>
                        <div class="col-md-9">
                            <input type="password" name="password" />
                        </div>
                    </div>
                
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="התחברות" class="btn btn-default" />
                    </div>
                </div>
               
            }

        <br />
        <p> <a href="@Url.Action("Register", "UserAccount")" style="color: red;">הרשמת משתמש חדש</a>  </p>

        <p> <a href="@Url.Action("ChangePassword", "UserAccount")"  style="color: red;">שכחתי סיסמא</a>  </p>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

final/WebsiteMVC/Views/UserAccount/Register.cshtml
@model WebsiteMVC.Models.UserModel

@{
    ViewBag.Title = "Register";
}

<br />
@if (Model != null && !Model.register)
{
    <h2> אירעה שגיאה בהרשמה, נסה שוב </h2>
    <h2> @Model.registerError </h2>
}




<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h2> הרשמת משתמש רגיל לאתר </h2>
            <br />

        @using (Html.BeginForm("Register", "UserAccount", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <input type="hidden" name="returnUrl" value="@Request.Url.GetLeftPart(UriPartial.Authority)" />
                    <div class="form-group">
                        <div class="col-md-3">
                            שם פרטי:
                        </div>
                        <div class="col-md-9">
                            <input type="text" name="firstname" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">
                            שם משפחה:
                        </div>
                        <div class="col-md-9">
                            <input type="text" name="lastname" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            אי מייל:
                        </div>
                        <div class="col-md-9">
                            <input type="text" name="email" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">
                            שם משתמש:
                        </div>
                        <div class="col-md-9">
                            <input type="text" name="username" />
                        </div>
                    </div>


                    <div class="form-group">
                        <div class="col-md-3">סיסמא: </div>
                        <div class="col-md-9">
                            <input type="password" name="password" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">
                            אישור סיסמא:
                        </div>
                        <div class="col-md-9">
                            <input type="password" name="confirmpassword" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">
                           אני מעוניין לפתוח חשבון בעל עסק באתר 
                        </div>
                        <div class="col-md-9">
                            <input type="checkbox" name="isBusiness" value="True"  />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">
                        </div>
                        <div class="col-md-9">
                                <input type="submit" value="אני רוצה להצטרף עכשיו!" class="btn btn-default btn-primary" style="font-size: 17px;" />
                        </div>
                        </div>
                }
        </div>
    </div>
</div>


               

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}