final/final/Controllers/BidController.cs
using ClientMVC.Models;
using Parse;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClientMVC.Controllers
{
    public class BidController : Controller
    {
        
        // GET: Bid
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CreateBidLink(string groupId)
        {   
            TempData["groupId"] = groupId;
            return View();
        }

        /*
        step sizes are calculeted as following:
        - first step: 10% of max units
        - second step: also 10% of max units
        
        - now we take the units left. if bigger than 15, we devide by 3 and split equally between steps 3,4,5.
        if smaller than 15, we devide by 2 and split equally between steps 3,4.

        step 5 is not mandatory.
            
        */
        private int[] calculateStepSizes(int maxUints)
        {
            int unitsLeft = maxUints;
            int[] result = new int[5];
            //ceiling round's up the number
            result[1] = (int)Math.Ceiling(maxUints * 0.1);
            result[2] = result[1];

            unitsLeft = unitsLeft - (result[1] + result[2]);
            if (unitsLeft > 15)
            {
                int tmp = (int)Math.Ceiling((double)unitsLeft / 3);
                result[3] = tmp;
                result[4] = tmp;
                result[5] = unitsLeft - result[3] - result[4];
            }
            else
            {
                int tmp = (int)Math.Ceiling((double)unitsLeft / 2);
                result[3] = tmp;
                result[4] = unitsLeft - result[3];
            }

            return result;
        }

        private async System.Threading.Tasks.Task<ActionResult> CreateBid(FormCollection coll)
        {

            /*
            ParseObject myBusiness = await model.retrieveMyBusiness();

            double maxUints = Convert.ToDouble(coll[Constants.MAX_UNITS]);
            double originalPrice = Convert.ToDouble(coll[Constants.ORIGINAL_PRICE]);
            double priceStep1 = Convert.ToDouble(coll[Constants.PRICE_STEP_1]);
            double priceStep2 = Convert.ToDouble(coll[Constants.PRICE_STEP_2]);
            double priceStep3 = Convert.ToDouble(coll[Constants.PRICE_STEP_3]);
            double priceStep4 = Convert.ToDouble(coll[Constants.PRICE_STEP_4]);
            double priceStep5 = Convert.ToDouble(coll[Constants.PRICE_STEP_5]);
            string comments = coll[Constants.COMMENTS];
            double guarantee = Convert.ToDouble(coll[Constants.GUARANTEE]);
            bool shipping = Convert.ToBoolean(coll[Constants.SHIPPING]);

            string groupId = (string)TempData["groupId"];

            await model.createBid(myBusiness, groupId, maxUints, originalPrice, priceStep1, priceStep2, priceStep3, priceStep4, priceStep5, comments, guarantee, shipping);
            */
            return View();
        }

        public async void winningBidSelector(string groupId)
        {
            await selectWinningBid(groupId);
        }


        /*
        winning bid is determined by several parameters:
        1. select biggest difference between second and third prices steps, or between 3h and 4h.
        2. lowest price of the product (depends on max units)
        3. original price
        4. ability to deliver to maximum people (max units)
        5. does have shipping
        6. how much guarantee (if any)
        7. reviews of the business

        Each parameter is weighted with a certain percentage - specified in Constants class
        */
        private async System.Threading.Tasks.Task<bool> selectWinningBid(string groupId)
        {

            return true;

            //IEnumerable<ParseObject> bids = await model.retrieveBids(groupId);
            /*
            double maxScore = 0;
            ParseObject bestBid = null;

            double stepDifference = 0;
            double lowestPrice = 0;
            double startingPrice = 0;
            double deliveryCapability = 0;
            double shippingCapability = 0;
            double guaranteeCapability = 0;

            foreach (ParseObject bid in bids)
            {
                //step difference calculation
                double step2to3Difference = model.getBidPriceStep2(bid) - model.getBidPriceStep3(bid);
                double step3to4Difference = model.getBidPriceStep3(bid) - model.getBidPriceStep4(bid);
                if (step2to3Difference > step3to4Difference)
                    stepDifference = step2to3Difference * Constants.CALCULATION_STEPS_DIFFERENCE / 100;
                else
                    stepDifference = step3to4Difference * Constants.CALCULATION_STEPS_DIFFERENCE / 100;

                //lowest price calculation
                //not always there is a 5th step. if exsist - take it.
                if (bid.Get<double>(Constants.PRICE_STEP_5) != 0)
                    lowestPrice = model.getBidPriceStep5(bid) * Constants.CALCULATION_LOWEST_PRICE / 100;
                else
                    lowestPrice = model.getBidPriceStep4(bid) * Constants.CALCULATION_LOWEST_PRICE / 100;

                //starting price calculation
                startingPrice = model.getBidOriginalPrice(bid) * Constants.CALCULATION_STARTING_PRICE / 100;

                //delivery capability calculation
                deliveryCapability = model.getBidMaxUints(bid) * Constants.CALCULATION_DELIVERY_CAPABILITY / 100;

                //shipping capability calculation
                if (model.getBidShipping(bid) == true)
                    shippingCapability = Constants.CALCULATION_SHIPPING_CAPABILITY;
                else
                    shippingCapability = 0;

                //guarantee capability calculation
                guaranteeCapability = model.getBidGuarantee(bid) * Constants.CALCULATION_GUARANTEE_CAPABILITY / 100;

                //add review if necessary


                double score = stepDifference + lowestPrice + startingPrice + deliveryCapability + shippingCapability + guaranteeCapability;
                if (score > maxScore)
                {
                    maxScore = score;
                    bestBid = bid;
                }                   
             }

            try
            {
                await model.createWinningBid(bestBid);
                return true;
            }
            catch (Exception e)
            {
                //add log
                throw e;
            }*/
        }
    }
}

final/final/Controllers/BusinessController.cs
using ClientMVC.Models;
using Parse;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ClientMVC.Controllers
{
    public class BusinessController : Controller
    {
        private static readonly log4net.ILog logger = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);
        DAL.Model model = new DAL.Model();


        // GET: Business
        public ActionResult Dashboard()
        {
            ParseUser user = ParseUser.CurrentUser;
            bool isBusiness = model.isBusiness(user);
            if (isBusiness)
            {
                return View();
            }
            return RedirectToAction("Index", "Home");
        }

        //check if the difference between NOW and creation time of the group is under 24 horus
        private TimeSpan canBusinessOferBid(DateTime groupCreationTime)
        {
            TimeSpan ts = DateTime.Now - groupCreationTime;

            int differenceInDays = ts.Days;
            int differenceInHours = ts.Hours;
            if (differenceInDays == 0 && differenceInHours < 24)
                return ts;

            //if not
            return TimeSpan.Zero;
        }


        //return list of groups - waiting for bid! - that are relevant for this current business
        public async System.Threading.Tasks.Task<ActionResult> GroupsWitingForBid()
        {
            List<ParseObject> groups = new List<ParseObject>(); //return value
            List<string> products = new List<string>(); //return value
            List<TimeSpan> timeToOffer = new List<TimeSpan>(); //return value

            ParseObject myBusiness = await model.retrieveMyBusiness();

            IEnumerable<ParseObject> allGroups = await model.retrieveAllActiveGroups();

            foreach (ParseObject group in allGroups)
            {

                ParseObject product = await model.retrieveProductOfGroup(group);

                //extract business field from product
                IEnumerable<ParseObject> businesses = await model.businessesWhoHaveThisProduct(product);

                //check if my business has this particular product
                foreach (ParseObject business in businesses)
                {
                    if (myBusiness.ObjectId == business.ObjectId)
                    {
                        DateTime groupCreationTime = (DateTime)group.CreatedAt;
                        TimeSpan timeToOfferABid = canBusinessOferBid(groupCreationTime);

                        //if there is time to offer
                        if (timeToOfferABid != TimeSpan.Zero)
                        {
                            products.Add(model.getProductTitle(product));
                            groups.Add(group);
                            timeToOffer.Add(timeToOfferABid);
                        }
                    }
                }
            }
            ViewBag.groups = groups;
            ViewBag.products = products;
            ViewBag.timeToOffer = timeToOffer;

            return View();
        }

        //return a list of groups that the current business "won".
        public async System.Threading.Tasks.Task<ActionResult> MyActiveGroups()
        {
            List<double> originalPrices = new List<double>(); //return value
            List<string> comments = new List<string>(); //return value
            List<ParseObject> groups = new List<ParseObject>(); //return value
            List<int> users = new List<int>(); //return value

            ParseObject myBusiness = await model.retrieveMyBusiness();

            IEnumerable<ParseObject> winningBids = await model.retrieveWinningBids();

            //check if the winnign bid is my bid (from my business)
            foreach (ParseObject winningBid in winningBids)
            {
                ParseObject bid = await model.getBid(winningBid);

                string businessId = model.getBusinessIdOfBid(bid);

                if (businessId == myBusiness.ObjectId)
                {
                    double originalPrice = model.getBidOriginalPrice(bid);
                    string comment = model.getCommentsOfBid(bid);

                    ParseObject group = await model.retrieveGroupOfBid(bid);

                    //extract how many users are currently in the group
                    IEnumerable<ParseObject> groupUsers = await model.retrieveUsersOfGroup(group);

                    users.Add(groupUsers.Count());
                    originalPrices.Add(originalPrice);
                    comments.Add(comment);
                    groups.Add(group);
                }
            }
            ViewBag.groups = groups;
            ViewBag.originalPrices = originalPrices;
            ViewBag.comments = comments;
            ViewBag.users = users;

            return View();
        }


        public async System.Threading.Tasks.Task<ActionResult> MyProducts()
        {
            ParseObject myBusiness = await model.retrieveMyBusiness();
            IEnumerable<ParseObject> allMyProducts = await model.retrieveAllMyPoducts(myBusiness.ObjectId);

            List<string> products = new List<string>();

            //extract the title from each product
            foreach (ParseObject product in allMyProducts)
            {
                products.Add(model.getProductTitle(product));
            }

            ViewBag.products = products;
            return View();
        }

        public async System.Threading.Tasks.Task<ActionResult> AddProductLink()
        {

            //Query for the select Lists of Category, SubCategory & Product
            IEnumerable<ParseObject> categories = await model.retrieveCategories();
            IEnumerable<ParseObject> subCategories = await model.retrieveSubCategories();
            IEnumerable<ParseObject> products = await model.retrieveAllProducts();

            //Names of products, categories and subcategories. Will move to parse controller...
            List<string> productsNames = new List<string>();
            List<string> categoriesNames = new List<string>();
            List<string> subCategoriesNames = new List<string>();
            foreach (ParseObject c in categories)
                categoriesNames.Add(c.Get<string>(Constants.NAME));
            foreach (ParseObject sc in subCategories)
                subCategoriesNames.Add(sc.Get<string>(Constants.NAME));
            foreach (ParseObject p in products)
                productsNames.Add(p.Get<string>(Constants.TITLE));


            //ViewBags sent to the view
            ViewBag.Categories = categories;
            ViewBag.SubCategories = subCategories;
            ViewBag.Products = products;
            ViewBag.ProductsNames = productsNames;
            ViewBag.CategoriesNames = categoriesNames;
            ViewBag.SubCategoriesNames = subCategoriesNames;

            return View();
        }

        public async System.Threading.Tasks.Task<ActionResult> AddProductToBusiness(FormCollection coll)
        {
            TempData["NewGroupCreated"] = null;

            //User wants to open new group of those parameters:
            string selectedCategory = coll[Constants.CATEGORY_ID];
            string selectedSubCategory = coll[Constants.SUB_CATEGORY_ID];
            string selectedProduct = coll[Constants.PRODUCT_ID];

            ParseObject myBusiness = await model.retrieveMyBusiness();

            await model.addProductToBusiness(selectedProduct, myBusiness);
            await model.addBusinessToProduct(selectedProduct, myBusiness);

            //TODO return myproducts list - below is not working
            return await MyProducts();
        }


        }
    }

final/final/Views/Business/AddProductLink.cshtml
@{
    ViewBag.Title = "CreateGroup";
    List<string> productsNames = ViewBag.ProductsNames;
    List<string> categoriesNames = ViewBag.CategoriesNames;
    List<string> subCategoriesNames = ViewBag.SubCategoriesNames;
    int productsNamesIndex = 0, categoriesNamesIndex = 0, subCategoriesNamesIndex = 0;

}
<h2>יצירת קבוצה</h2>

<br /><br />
<div style="float:right; direction:rtl;">
    @using (Html.BeginForm("AddProductToBusiness", "Business", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            קטגוריה
            <div class="col-md-9">
                <select name="CategoryID" style="width: 200px;">
                    <option value="0">ללא</option>
                    @foreach (var category in ViewBag.Categories)
                    {
                        <option value="@category.ObjectId">@categoriesNames[categoriesNamesIndex]</option>
                        categoriesNamesIndex++;
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            תת-קטגוריה
            <div class="col-md-9">
                <select name="SubCategoryID" style="width: 200px;">
                    <option value="0">ללא</option>
                    @foreach (var subcategory in ViewBag.SubCategories)
                    {
                        <option value="@subcategory.ObjectId">@subCategoriesNames[subCategoriesNamesIndex]</option>
                        subCategoriesNamesIndex++;
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            מוצר
            <div class="col-md-9">
                <select name="ProductID" style="width: 200px;">
                    <option value="0">ללא</option>
                    @foreach (var product in ViewBag.Products)
                    {
                        <option value="@product.ObjectId">@productsNames[productsNamesIndex]</option>
                        productsNamesIndex++;
                    }
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="יצירה" />
            </div>
        </div>
    }



</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


final/final/Views/Business/AddProductToBusiness.cshtml

@{
    ViewBag.Title = "AddProductToBusiness";
}

<h2>AddProductToBusiness</h2>

<script>

    var businessId = '@(ViewBag.myBusinessId)';
    var selectedProduct = '@(ViewBag.selectedProduct)';
    var product = '@(ViewBag.product)';
    var business = Parse.Object.extend("Business");
    var query = new Parse.Query(business);
    query.get(businessId, {
        success: function (business) {
            // The object was retrieved successfully.
            var relation = business.relation("products");
            relation.add(product);
            business.save();
        },
        error: function (object, error) {
            // The object was not retrieved successfully.
            // error is a Parse.Error with an error code and message.
        }
    });



</script>


final/final/Views/Business/Dashboard.cshtml
@{
    ViewBag.Title = "Dashboard";
}

<div class="jumbotron">
    <h1>פאנל ניהול לבעלי עסקים</h1>
    </div>

<div class="row">
    <div class="col-md-4">
        <h2><a href="@Url.Action("GroupsWitingForBid","Business")">קבוצות ממתינות להצעת מחיר</a></h2>
    </div>
    <div class="col-md-4">
        <h2><a href="@Url.Action("MyActiveGroups","Business")">קבוצות פעילות שלי</a></h2>
    </div>
    <div class="col-md-4">
        <h2><a href="@Url.Action("MyProducts","Business")">המוצרים שלי</a></h2>
    </div>
</div>

final/final/Views/Business/GroupsWitingForBid.cshtml

@{
    ViewBag.Title = "GroupsWitingForBid";
    int i = 0;
    List<string> products = ViewBag.products;
    List<TimeSpan> timeToOffer = ViewBag.timeToOffer;
}


        <table class="table">
            <tr>
                <th>קבוצה</th>
                <th>מוצר</th> 
                <th>זמן נותר להצעת מחיר</th>
                <th>משתמשים</th>
                <th>הגש הצעה</th>
                

            </tr>
            
            @foreach (var group in ViewBag.groups)
            {
                <tr>
                    <td>
                        @group.ObjectId
                    </td>
                   
                    <td>
                        @products.ElementAt(i)
                    </td>
                   <td>
                      @timeToOffer.ElementAt(i) 
                   </td>
                    <td>

                    </td>
                    <td>
                        @Html.ActionLink("הגש הצעה", "CreateBidLink", "Bid" , new { groupId = group.ObjectId },null)
                    </td>
                </tr>
                i++;
            }

        </table>


final/final/Views/Business/Login.cshtml
@using final.Models
@model LoginViewModel
@{
    ViewBag.Title = "Log in";
}

<h2>@ViewBag.Title.</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.AntiForgeryToken()
                <h4>Use a local account to log in.</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(m => m.RememberMe)
                            @Html.LabelFor(m => m.RememberMe)
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Register as a new user", "Register")
                </p>
                @* Enable this once you have account confirmation enabled for password reset functionality
                    <p>
                        @Html.ActionLink("Forgot your password?", "ForgotPassword")
                    </p>*@
            }
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm">
            @Html.Partial("_ExternalLoginsListPartial", new ExternalLoginListViewModel { ReturnUrl = ViewBag.ReturnUrl })
        </section>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

final/final/Views/Business/MyActiveGroups.cshtml

@{
    ViewBag.Title = "MyActiveGroups";
    int i = 0;
    List<string> comments = ViewBag.comments;
    List<double> originalPrices = ViewBag.originalPrices;
    List<int> users = ViewBag.users;
}


<table class="table">
    <tr>
        <th>קבוצה</th>
        <th>מחיר</th>
        <th>הערות</th>


    </tr>

    @foreach (var group in ViewBag.groups)
            {
        <tr>
            <td>
                @group.ObjectId
            </td>

            <td>
                @originalPrices.ElementAt(i)
            </td>
            <td>
                @comments.ElementAt(i)
            </td>
            <td>
                @users.ElementAt(i)
            </td>
        </tr>
        i++;
    }

</table>


final/final/Views/Business/MyProducts.cshtml

@{
    ViewBag.Title = "MyProducts";

}


<table class="table">
    <tr>
        <th>מוצר</th>


    </tr>

    @foreach (var product in ViewBag.products)
            {
        <tr>
            <td>
                @product
            </td>

        </tr>
    }

</table>
